<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style="font-size:16px;">Kebijakan Privasi</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";'>Tanggal Berlaku: 19 Juni 2025</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";'>Terima kasih telah menggunakan Manajemen Asetez. Kami menghargai privasi Anda dan berkomitmen untuk melindungi informasi pribadi Anda. Kebijakan Privasi ini menjelaskan bagaimana kami mengumpulkan, menggunakan, dan melindungi data Anda.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style="font-size:13px;border:solid #E5E7EB 1.0pt;padding:0cm;">Informasi yang Kami Kumpulkan</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Kami dapat mengumpulkan berbagai jenis informasi dari dan tentang pengguna aplikasi kami, termasuk:&nbsp;</span></p>
<ol style="list-style-type: decimal;">
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Informasi Pribadi: Nama, alamat email, nomor telepon, dan informasi lain yang Anda berikan secara sukarela.</span></li>
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Informasi Penggunaan: Data tentang bagaimana Anda berinteraksi dengan aplikasi kami, termasuk jenis perangkat, sistem operasi, dan data penggunaan lainnya.</span></li>
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Data Lokasi: Informasi tentang lokasi Anda, jika Anda mengizinkan akses ke data lokasi Anda.</span></li>
</ol>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:13px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Cara Kami Menggunakan Informasi</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Informasi yang kami kumpulkan dapat digunakan untuk:</span></p>
<ol style="list-style-type: decimal;">
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Menyediakan dan mengelola layanan kami.</span></li>
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Memperbaiki aplikasi kami dan menyesuaikan pengalaman pengguna.</span></li>
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Mengirimkan pemberitahuan, pembaruan, dan komunikasi lainnya terkait dengan aplikasi.</span></li>
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Menganalisis penggunaan aplikasi untuk memahami tren dan preferensi pengguna.</span></li>
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Melindungi keamanan dan integritas aplikasi kami.</span></li>
</ol>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:13px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Berbagi Informasi</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Kami tidak akan membagikan informasi pribadi Anda kepada pihak ketiga, kecuali dalam situasi berikut:</span></p>
<ol style="list-style-type: decimal;">
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Dengan persetujuan Anda.</span></li>
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Untuk mematuhi kewajiban hukum, peraturan, atau proses hukum.</span></li>
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Untuk melindungi hak, properti, atau keselamatan kami atau pengguna kami.</span></li>
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Dengan penyedia layanan pihak ketiga yang membantu kami dalam menjalankan aplikasi kami, dengan syarat mereka setuju untuk menjaga kerahasiaan informasi Anda.</span></li>
</ol>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:13px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Keamanan Data</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Kami menerapkan langkah-langkah keamanan yang wajar untuk melindungi informasi pribadi Anda dari akses, penggunaan, atau pengungkapan yang tidak sah. Namun, tidak ada metode transmisi data melalui internet atau metode penyimpanan elektronik yang 100% aman.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:13px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Hak Anda</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Anda memiliki hak untuk:</span></p>
<ol style="list-style-type: decimal;">
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Mengakses dan memperbarui informasi pribadi Anda.</span></li>
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Meminta penghapusan informasi pribadi Anda.</span></li>
    <li><span style='font-family:"Segoe UI","sans-serif";font-size:9px;'>Menolak atau membatasi pemrosesan informasi pribadi Anda.</span></li>
</ol>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Untuk menggunakan hak-hak ini, silakan hubungi kami di wibisonopraja@gmail.com</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:13px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Perubahan pada Kebijakan Privasi</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Kami dapat memperbarui Kebijakan Privasi ini dari waktu ke waktu. Perubahan akan diberlakukan segera setelah kebijakan yang diperbarui diposting di aplikasi kami. Kami akan memberi tahu Anda tentang perubahan signifikan melalui email atau pemberitahuan di aplikasi kami.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:13px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Hubungi Kami</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:9px;font-family:"Segoe UI","sans-serif";border:solid #E5E7EB 1.0pt;padding:0cm;'>Jika Anda memiliki pertanyaan atau kekhawatiran tentang Kebijakan Privasi ini, silakan hubungi kami di: wibisonopraja@gmail.com ,Pastikan untuk meninjau kebijakan ini secara berkala dan memperbaruinya sesuai dengan perubahan dalam praktik pengumpulan data atau peraturan privasi yang berlaku.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";'>&nbsp;</p>